### ISSUE TITLE
How to deal with European NDC and NPi formulations in SSP1, SSP5, SDP and SSP2_lowenergy scenarios

### ISSUE THREAD

**Issue by Renato-Rodrigues** [remindmodel/remind#1243]
The pull request https://github.com/remindmodel/remind/pull/1239 changed NPi and NDC definition of Europe carbon pricing in all SSP2 scenarios to follow EU21 representation of European targets:
- NPi = 40% reduction of emissions by 2030
- NDC = 55% reduction of emissions by 2030
- both using a low ambition energy efficiency target using `cm_implicitQttyTarget`.

No change was made to `SSP1`, `SSP5`, `SDP_MC`, `SDP_EI`, `SDP_RC`, `SSP2 lowEnergy` scenarios and a decision must be made to keep consistency in the scenario config. 

The simple solution would be to assume the SSP2 parametrizations detailed above for all NPi and NDC formulations, no matter the scenario. However, as these assumptions goes further into future time steps, people that work with those scenarios should make the final decision.

@bs538 , @LaviniaBaumstark , @nicobauer

**Comment by bs538** [comment]
Thanks Renato. Generally I would see NPi and NDC as reflections of real-world policies (policy announcements), which should be reflected in all our scenarios. So your simple solution also seems the conceptually right choice.
Specifically to the SDP_XX scenarios. We don't really use the SDP_XX-NDC as it is a bit of a strange world (full sustainability but no strong climate policy), so I'm not fuzzed about this anyhow. The NPi scenarios we do use as reference scenarios. Do you happen to have a plot / number at hand how much the new NPi changes compared to the old NPi?

**Comment by Renato-Rodrigues** [comment]
> Do you happen to have a plot / number at hand how much the new NPi changes compared to the old NPi?

I don't have that at hand, as this requires the calibrations that Lavinia is making available just now in this PR https://github.com/remindmodel/remind/pull/1251.
As soon as the next AMT runs are available, you can check those by yourself by simply comparing the new results with the previous ones, at least for the SSP2 scenarios. The AMT creates automatically scenario comparison pdfs in relation with the previous week as far as I know. Just be aware that any new results will also include the new deltacap formulation.

For any other scenario (SDP, SSP1,...), I assume you and others more knowledged about these scenarios to become responsible to adapt the scenario config files accordingly so the upcoming results keep consistence between our formulations.

**Comment by bs538** [comment]
Only getting back to this now because of proposal writing etc... 

Looking at the current scenario_config.csv I see that so far these changes are still only in SSP2 and SSP2-EU21. @LaviniaBaumstark @nicobauer do you agree that this should become the default for all scenarios? I wouldn't want to do it only for the SDPs if we don't do it for SSP1 etc.

@Renato-Rodrigues I see a bunch of EU specific modifications to the config (columns regipol to cm_altEmiFac). Do all of these need to be ported to all other scenarios? or just the two colums regarding cm_implicitQttyTarget?

**Comment by LaviniaBaumstark** [comment]
> Looking at the current scenario_config.csv I see that so far these changes are still only in SSP2 and SSP2-EU21. @LaviniaBaumstark @nicobauer do you agree that this should become the default for all scenarios? I wouldn't want to do it only for the SDPs if we don't do it for SSP1 etc.

sure, if @orichters agrees, I am not familiar with NDC versions

**Comment by bs538** [comment]
@LaviniaBaumstark @orichters @Renato-Rodrigues I guess we need to come to a conclusion here also for the release? It doesn't matter for calibrating but for doing non-SSP2 policy runs it matters

**Comment by Renato-Rodrigues** [comment]
> @Renato-Rodrigues I see a bunch of EU specific modifications to the config (columns regipol to cm_altEmiFac).

`cm_altEmiFac` was introduced to avoid negative emissions in specific REMIND 21 regions due to the problems with emission factors and non_energy handling in the model. See: 
https://github.com/remindmodel/development_issues/issues/20#issuecomment-892690983

The aggregated EUR in H12 probably hides this issue, but as my recommendations to fix this issue were still not implemented (https://github.com/remindmodel/development_issues/issues/20#issuecomment-1167104515), I would suggest to use the same formulation as in REMIND 21 (remind-eu) SSP2 for now.

**Comment by bs538** [comment]
I adapted the config so that the non-SSP2 scenarios follow the model of the respective Base / NDC / NPi / PkBudg scenario for SSP2EU-H12 for the following colums:
regipol | cm_implicitQttyTarget | cm_loadFromGDX_implicitQttyTargetTax | cm_emiMktTarget | cm_NucRegiPol | cm_CoalRegiPol | cm_altFeEmiFac

@Renato-Rodrigues your response above refers only to cm_altFeEmiFac, can you confirm that the above is what you intended? config is here if you want to have a look:
/p/projects/piam/SHAPE_runs/REMIND_calibrateSDPs_2023-04-12/config/scenario_config.csv


@robertpietzcker @LaviniaBaumstark @orichters @nicobauer 
I simply copied Renato's changes for NDC / NPi / PkBudg without really knowing what they do (besides what you can infer from switch name and value). Test runs are underway for SDP_XX and SSP1 (which I need for SHAPE). I don't have the capacity to also do SSP2-lowEn and SSP5, so someone else would have to take responsibility for that. 

Do we want this change in config, to maintain consistency between SSP2 and other scenarios in the release? If results look OK I would say yes. Would mean new validation runs for non-SSP2 scenarios though. Only change to Base config is the cm_altEmiFac, everything else only affects NPi / NDC / PkBudg. So hopefully (?) no new calibration needed. And, as Renato says, it's likely mostly hidden at H12 level anyhow.

**Comment by Renato-Rodrigues** [comment]
You can always read the descriptions of the switches in the main.gms. :)
They should have enough info so you understand what they do, and in case not, you should create an issue asking for more details so the descriptions can be improved.

- `cm_implicitQttyTarget` use is explained in the first post of this issue (sets a low ambition European energy efficiency target, the legislation in place is already stronger than this target). 
- `cm_loadFromGDX_implicitQttyTargetTax` is just used to initialize the above target in the first iteration in policy runs, to avoid unecessarily starting from a point farther away from the solution.
- `cm_emiMktTarget` use is explained in the first post of this issue (sets a 40% NPi and 55% NDC target for EUR at 2030). 
- `cm_NucRegiPol` and `cm_CoalRegiPol` enable legislative specific boundaries for nuclear and coal usage in certain regions. For now, they should only make a difference for REMIND 21 regions, but enabling them in all scenarios is better in general terms as this will be probably extended for other regions in the future, unless your scenario implies not abidding by these regulations that are at place.
-  `cm_altFeEmiFac` was already explained in the above message.

**Comment by bs538** [comment]
Thanks Renato. Is now incorporated here https://github.com/remindmodel/remind/pull/1293

As we all agreed that it makes sense to align the scenarios concerning the EU switches: If you make changes to those switches in the future, could you apply them also to the non-SSP2 scenarios so that we keep the consistent set? @Renato-Rodrigues @robertpietzcker
