### ISSUE TITLE
avoid future renv issues for coupled runs

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#1409]
while #1407 is fixed now, we should try to avoid such complications in the future

- REMIND-MAgPIE runs should behave in the same way as REMIND standalone with respect to renv
- [This line](https://github.com/remindmodel/remind/blob/712dec7ec3903272f46a1d97c7fc1c01e9d2f3af/scripts/start/submit.R#L52) seems to evaluate to `TRUE` for every REMIND-MAgPIE run, which I think it shouldn't. I guess it is because coupled runs have the REMIND main folder as working directory.
- This results in the `renv` code below being executed on the compute nodes which failed, while it works on the login nodes. Not sure whether that also means that `renv` does not work as intended at the moment.

suggestions:
- move the renv checks from [submit.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/submit.R#L46-L96) to an own function in `scripts/start/`
- only call the checks, snapshot generation etc. it in `start.R` and `start_bundle_coupled.R`, not in `submit()` to avoid failing runs
- idea: for subsequent runs in a cascade (for both standalone and REMIND-MAgPIE), copy the renv stuff not from the main folder, but from the folder that starts the run, to guarantee that all the cascade runs on the same renv

**Comment by dklein-pik** [comment]
I prepared this PR #1455 to suggest a way of detecting the first run of a cascade that should work for standalone *and* coupled runs. What do you think?

**Comment by dklein-pik** [comment]
Regarding the (login/compute)-node issue: I think we cannot avoid that some of the renv commands (init, restore) are executed on the compute node, because subsequent runs are started from there. However, when called for the first time, `submit(cfg)` and the embedded renv commands (in particular snapshot) are executed on the login-node, since [these lines](https://github.com/remindmodel/remind/blob/e5747f428a2d5a0a9a518fefe73fee140b884784/scripts/start/submit.R#L51C1-L76C1) in submit.R are
executed before the actual slurm job (`prepareAndRun()`) is submitted.
