### ISSUE TITLE
full.lst lagging considerably behind full.log

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#170]
Why is it that full.log reports being at the 12th iteration whereas full.lst hasn't even started reporting the first one? Does anyone have an idea?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
As far as I can tell because the listing file is written to a memory buffer that isn't flushed to disk regularly.  Probably that's controlled by the OS and not GAMS.  That's the reason Antoine and I include lots of `putclose logfile;` in the calibration, because that forces the file buffer to be written out.  
You can search for some arcane command or option to force writing of the buffer, but we found none and gave up searching three years ago or so. 

You can try opening to listing file to append to it, then closing it again:
```
file listfile /"full.lst"/;
listfile.ap = 1;

put listfile;
putclose listfile;
```
But I have no idea whether that even works and if it corrupts the listing file or not.
If you are desperate for some information, write it to a `.put` file instead.

**Comment by johanneskoch94** [comment]
Sry, I've got nothing on this.

**Comment by giannou** [comment]
> As far as I can tell because the listing file is written to a memory buffer that isn't flushed to disk regularly. Probably that's controlled by the OS and not GAMS. That's the reason Antoine and I include lots of `putclose logfile;` in the calibration, because that forces the file buffer to be written out.
> You can search for some arcane command or option to force writing of the buffer, but we found none and gave up searching three years ago or so.
> 
> You can try opening to listing file to append to it, then closing it again:
> 
> ```
> file listfile /"full.lst"/;
> listfile.ap = 1;
> 
> put listfile;
> putclose listfile;
> ```
> 
> But I have no idea whether that even works and if it corrupts the listing file or not.
> If you are desperate for some information, write it to a `.put` file instead.

Thanks! Super helpful
