### ISSUE TITLE
Region hard-coded

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#362]
Any chance these can be formulated otherwise? We don't want hard-coded regions, right?

https://github.com/remindmodel/remind/blob/8b57befa78c5922e9bf9e368c2d1e68849aef584/modules/21_tax/on/datainput.gms#L192

https://github.com/remindmodel/remind/blob/8b57befa78c5922e9bf9e368c2d1e68849aef584/modules/21_tax/on/datainput.gms#L261

**Comment by Renato-Rodrigues** [comment]
Anything with _regi in the set name is not really a hard coded region.
This is a set subgroup created dynamically that will group any subregions that aggregated together is equal to a H12 region. As far as I know, H12 should be our lower level of aggregation for REMIND regions, so they simply act as subsets for H12 specific code.

So, for example:
- for H12 -> EUR_regi = EUR
- for REMIND-EU -> EUR_regi = (ENC,EWN,ECS,ESC,ECE,FRA,DEU,UKI,ESW).
- and for any other region aggregation used in the future, ex. a potential full split of EU countries, EUR_regi will be calculated dynamically in R and updated in the gams code to correspond to the regions that sum up to the original EU region. 

One could move the code for the biomass tax to the regipol module instead of the taxes module if you don't want references that use this subset in the tax modules. However, I think this could be counterproductive as it would just put related code in two different modules instead of concentrating it on the same module.

**Comment by giannou** [comment]
I though so, thanks. Where is the part about H12 being the lowest level of aggregation for REMIND documented? I have managed to generate the input data for a 2-region world (USA and rest) and want to start a REMIND run with it now so I can finally have a fulldata.gdx with only 2 regions that would increase the speed of our output tests

**Comment by Renato-Rodrigues** [comment]
on the H12 being the lowest level of aggregation for REMIND, it was just an assumption that I made based on the mappings that we had and the way we create input data for fossils and other related data. I don't think there is actually a documentation saying expressly that. 

I can see the problem with creating a test version with less than 12 regions. I am afraid you would need to create an exception in the prepare_and_run script to create this region subset with empty elements instead, or use europe as one your two regions instead.

**Comment by Renato-Rodrigues** [comment]
In the gams part of the code it should work, as this subset was introduced to deal with REMIND-EU specific code changes and it is only used so far, as far as I know, for EUR_regi.

Even so, you are in uncharted waters. If there is any error related with that on gams, just let me know and I can try to help figuring out a work around.

**Comment by giannou** [comment]
Ok changing to (EUR,  rest) worked*, but I think it'd be nice if the model had more flexibility in the regional resolution.

*: to make it work I had to delete these two lines
https://github.com/remindmodel/remind/blob/8b57befa78c5922e9bf9e368c2d1e68849aef584/modules/37_industry/fixed_shares/datainput.gms#L50
https://github.com/remindmodel/remind/blob/8b57befa78c5922e9bf9e368c2d1e68849aef584/modules/37_industry/fixed_shares/datainput.gms#L51
(so there are still some hard-coded regions after all)

**Comment by Renato-Rodrigues** [comment]
In order to avoid those lines to cause problems in the future they should be written like this:

```
pm_ppfen_shares(t,regi,"enhi","fehei")$(sameas(regi,"REF")) = 0.3; 
pm_ppfen_shares(t,regi,"enhi","fehei")$(t.val le 2030 and (sameas(regi,"REF"))) = 0.50 - (0.20/25)*(t.val-2005); 
```
I can commit this change once I finish working in other stuff. This is, if you don't beat me to do it before. :)

I agree that we should avoid region specific conditions in the code. People should dedicate some time to check where they appear and think about alternative formulations, additional input data, or other alternatives.
Although I show as the last person that changed those lines, for many cases like this one I just rewrote previous code to be compatible with the current REMIND formulation or more up to date data.

**Comment by giannou** [comment]
solved with https://github.com/remindmodel/remind/commit/867c0da3fe6e06135f72faa124c685755896f4c1
